# Common configuration for SimpleCov for both RSpec and bin/fig.

SimpleCov.merge_timeout 2 * 60 * 60 # 2 hours

# Need a custom filter because bin/fig gets run with a different current
# directory.
class FigFileFilter < SimpleCov::Filter
  def matches?(source_file)
    return source_file.filename =~ %r< \b spec \b | \b vendor \b >x
  end
end
SimpleCov.add_filter FigFileFilter.new(nil)


SimpleCov.add_group 'Controller',
  '(?x) lib/fig/ command (?: [.]rb | / )'

SimpleCov.add_group 'Model',
  '(?x) lib/fig/ (?: package (?: _descriptor | ) [.]rb | statement (?: [.]rb | _container | / ) )'

SimpleCov.add_group 'Package runtime environment',
  '(?x) lib/fig/ (?: environment_variables | grammar_monkey_patches | include_backtrace | runtime_environment | working_directory )'

SimpleCov.add_group 'Package management',
  '(?x) lib/fig/ (?: repository | package_cache | package_definition | [^/]* parse [^/]* $ | unparser/ )'

SimpleCov.add_group 'Fig environment/config',
  '(?x) lib/fig/ (?: application_configuration | config_file| figrc | url_access_error )'

SimpleCov.add_group 'I/O',
  '(?x) lib/fig/ (?: at_exit | log (?: 4r | ging ) | network | not_found | operating_system | protocol | update_lock )'

SimpleCov.add_group 'Utilities',
  '(?x) lib/fig/ (?: tokenized_string | string_tokenizer | url[.]rb )'

SimpleCov.add_group 'Generated by Treetop',
  '(?x) lib/fig/ grammar/'
